datadog:
  apiKeyExistingSecret: datadog-secret
  site: datadoghq.com
  clusterName: oficina-fase3
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    portEnabled: true
  processAgent:
    enabled: true
    processCollection: true
  kubeStateMetricsCore:
    enabled: true
  orchestratorExplorer:
    enabled: true

clusterAgent:
  enabled: true
  metricsProvider:
    enabled: true
